name: costeosmart
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_analytics: ^12.0.0

  # State Management
  get: ^4.6.6
  
  # UI/UX
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.3
  animations: ^2.0.11
  shimmer: ^3.0.0
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.2.2
  shared_preferences: ^2.2.2
  
  # Forms & Validation
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  
  # Charts & Analytics
  fl_chart: ^1.0.0
  
  # Images
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  
  # Icons
  flutter_phosphor_icons: ^0.0.1+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  


flutter:
  uses-material-design: true
